# Generated by Django 4.0.3 on 2022-04-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='user',
        ),
    ]
