# Generated by Django 4.0.3 on 2022-04-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_incidentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(choices=[('80', '80'), ('443', '443'), ('3389', '3389'), ('3306', '3306'), ('25', '25')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('syslog', 'syslog'), ('kern.log', 'kern.log'), ('auth.log', 'auth.log'), ('dpkg.log', 'dpkg.log')], max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='port',
        ),
    ]
