# Generated by Django 4.0.3 on 2022-04-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_port_system_remove_incidentreport_port'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='System',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='port',
            field=models.CharField(choices=[('80', '80'), ('443', '443'), ('3389', '3389'), ('3306', '3306'), ('25', '25')], default='1', max_length=6),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='system',
            field=models.CharField(choices=[('syslog', 'syslog'), ('kern.log', 'kern.log'), ('auth.log', 'auth.log'), ('dpkg.log', 'dpkg.log')], default='1', max_length=12),
        ),
    ]
