# Generated by Django 4.0.3 on 2022-04-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_port_delete_system_incidentreport_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='port',
            field=models.IntegerField(choices=[(80, 'Port80'), (443, 'Port443'), (3389, 'Port3389'), (3306, 'Port3306'), (25, 'Port25')]),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='system',
            field=models.TextField(choices=[('syslog', 'Syslog'), ('kern.log', 'Kernlog'), ('auth.log', 'Authlog'), ('dpkg.log', 'Dpkg')]),
        ),
    ]
