# Generated by Django 4.0.3 on 2022-04-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_incidentreport_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='tactic',
            field=models.CharField(choices=[('Reconnaissance', 'Reconnaissance'), ('Resource Development', 'Resource Development'), ('Initial Access', 'Initial Access'), ('Execution', 'Execution'), ('Persistence', 'Persistence'), ('Privilege Escalation', 'Privilege Escalation'), ('Defense Evasion', 'Defense Evasion'), ('Credential Access', 'Credential Access'), ('Discovery', 'Discovery'), ('Lateral Movement', 'Lateral Movement'), ('Collection', 'Collection'), ('Command and Control', 'Command And Control'), ('Exfiltration', 'Exfiltration'), ('Impact', 'Impact')], default='Collection', max_length=60),
        ),
    ]
