# Generated by Django 4.0.3 on 2022-04-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_incidentreport_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
