# Generated by Django 4.0.3 on 2022-04-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_incidentreport_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='created_at',
        ),
    ]
