# Generated by Django 4.0.3 on 2022-04-02 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_incidentreport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
