# Generated by Django 4.0.3 on 2022-04-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_incidentreport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='port',
            field=models.IntegerField(blank=True, choices=[(80, 'P80'), (443, 'P443'), (3389, 'P3389'), (3306, 'P3306'), (25, 'P25')]),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='system',
            field=models.TextField(blank=True, choices=[('syslog', 'Syslog'), ('kern.log', 'Kernlog'), ('auth.log', 'Authlog'), ('dpkg.log', 'Dpkg')]),
        ),
    ]
