# Generated by Django 4.0.3 on 2022-04-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_incidentreport_port_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='created_at',
            new_name='attack_time',
        ),
    ]
