# Generated by Django 4.0.3 on 2022-04-04 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_created_at_incidentreport_attack_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
