# Generated by Django 4.0.3 on 2022-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_incidentreport_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWaterfallGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.JSONField()),
            ],
        ),
    ]
