# Generated by Django 4.0.3 on 2022-04-08 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mainwaterfallgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainwaterfallgraph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
